services:
    web:
        networks:
            uninuvola:
                ipv4_address: $WEB_IP
        container_name: web
        image: web
        build: ./
        env_file: .env

networks:
  uninuvola:
    external: true
