services:
    web:
        dns:
          - ${DNS_IP}
        networks:
            uninuvola:
                ipv4_address: ${WEB_IP}
        container_name: web
        image: harbor1.fisgeo.unipg.it/uninuvola/web:main
        env_file: ../.env

networks:
  uninuvola:
    external: true
