services:
    vault:
        container_name: vault
        ports:
            - 8200:8200
        environment:
            - VAULT_DEV_ROOT_TOKEN_ID=dev-only-token
            - VAULT_ADDR=http://0.0.0.0:8200
        image: hashicorp/vault
        # volumes: 
        #     - vault:/

# volumes:
#     vault: {}
