services:
    vault:
        cap_add:
            - IPC_LOCK
        container_name: vault
        ports:
            - 8200:8200
        environment:
            - 'VAULT_LOCAL_CONFIG={"storage": {"file": {"path": "/vault/file"}},
              "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable":
              true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h",
              "ui": true}'
            # - VAULT_DEV_ROOT_TOKEN_ID=dev-only-token
            - VAULT_ADDR=http://0.0.0.0:8200
        image: hashicorp/vault
        command: server
        volumes: 
            - vault:/vault/

volumes:
    vault: {}
